[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://*.typekit.net; font-src https://*.typekit.net; img-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'self'"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=15768000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"